pub enum KusamaRpcMethod {
	AccountNextIndex,
	AuthorHasKey,
	AuthorHasSessionKeys,
	AuthorInsertKey,
	AuthorPendingExtrinsics,
	AuthorRemoveExtrinsic,
	AuthorRotateKeys,
	AuthorSubmitAndWatchExtrinsic,
	AuthorSubmitExtrinsic,
	AuthorUnwatchExtrinsic,
	BabeEpochAuthorship,
	BeefyGetFinalizedHead,
	BeefySubscribeJustifications,
	BeefyUnsubscribeJustifications,
	ChainHeadUnstableBody,
	ChainHeadUnstableCall,
	ChainHeadUnstableFollow,
	ChainHeadUnstableGenesisHash,
	ChainHeadUnstableHeader,
	ChainHeadUnstableStorage,
	ChainHeadUnstableUnfollow,
	ChainHeadUnstableUnpin,
	ChainGetBlock,
	ChainGetBlockHash,
	ChainGetFinalisedHead,
	ChainGetFinalizedHead,
	ChainGetHead,
	ChainGetHeader,
	ChainGetRuntimeVersion,
	ChainSubscribeAllHeads,
	ChainSubscribeFinalisedHeads,
	ChainSubscribeFinalizedHeads,
	ChainSubscribeNewHead,
	ChainSubscribeNewHeads,
	ChainSubscribeRuntimeVersion,
	ChainUnsubscribeAllHeads,
	ChainUnsubscribeFinalisedHeads,
	ChainUnsubscribeFinalizedHeads,
	ChainUnsubscribeNewHead,
	ChainUnsubscribeNewHeads,
	ChainUnsubscribeRuntimeVersion,
	ChildstateGetKeys,
	ChildstateGetKeysPaged,
	ChildstateGetKeysPagedAt,
	ChildstateGetStorage,
	ChildstateGetStorageEntries,
	ChildstateGetStorageHash,
	ChildstateGetStorageSize,
	GrandpaProveFinality,
	GrandpaRoundState,
	GrandpaSubscribeJustifications,
	GrandpaUnsubscribeJustifications,
	MmrGenerateProof,
	MmrRoot,
	MmrVerifyProof,
	MmrVerifyProofStateless,
	OffchainLocalStorageGet,
	OffchainLocalStorageSet,
	PaymentQueryFeeDetails,
	PaymentQueryInfo,
	StateCall,
	StateCallAt,
	StateGetChildReadProof,
	StateGetKeys,
	StateGetKeysPaged,
	StateGetKeysPagedAt,
	StateGetMetadata,
	StateGetPairs,
	StateGetReadProof,
	StateGetRuntimeVersion,
	StateGetStorage,
	StateGetStorageAt,
	StateGetStorageHash,
	StateGetStorageHashAt,
	StateGetStorageSize,
	StateGetStorageSizeAt,
	StateQueryStorage,
	StateQueryStorageAt,
	StateSubscribeRuntimeVersion,
	StateSubscribeStorage,
	StateTraceBlock,
	StateTrieMigrationStatus,
	StateUnsubscribeRuntimeVersion,
	StateUnsubscribeStorage,
	SubscribeNewHead,
	SyncStateGenSyncSpec,
	SystemAccountNextIndex,
	SystemAddLogFilter,
	SystemAddReservedPeer,
	SystemChain,
	SystemChainType,
	SystemDryRun,
	SystemDryRunAt,
	SystemHealth,
	SystemLocalListenAddresses,
	SystemLocalPeerId,
	SystemName,
	SystemNodeRoles,
	SystemPeers,
	SystemProperties,
	SystemRemoveReservedPeer,
	SystemReservedPeers,
	SystemResetLogFilter,
	SystemSyncState,
	SystemUnstableNetworkState,
	SystemVersion,
	TransactionUnstableSubmitAndWatch,
	TransactionUnstableUnwatch,
	UnsubscribeNewHead,
}

impl KusamaRpcMethod {
	pub fn as_string(&self) -> String {
		match self {
			KusamaRpcMethod::AccountNextIndex => "account_nextIndex".to_string(),
			KusamaRpcMethod::AuthorHasKey => "author_hasKey".to_string(),
			KusamaRpcMethod::AuthorHasSessionKeys => "author_hasSessionKeys".to_string(),
			KusamaRpcMethod::AuthorInsertKey => "author_insertKey".to_string(),
			KusamaRpcMethod::AuthorPendingExtrinsics => "author_pendingExtrinsics".to_string(),
			KusamaRpcMethod::AuthorRemoveExtrinsic => "author_removeExtrinsic".to_string(),
			KusamaRpcMethod::AuthorRotateKeys => "author_rotateKeys".to_string(),
			KusamaRpcMethod::AuthorSubmitAndWatchExtrinsic =>
				"author_submitAndWatchExtrinsic".to_string(),
			KusamaRpcMethod::AuthorSubmitExtrinsic => "author_submitExtrinsic".to_string(),
			KusamaRpcMethod::AuthorUnwatchExtrinsic => "author_unwatchExtrinsic".to_string(),
			KusamaRpcMethod::BabeEpochAuthorship => "babe_epochAuthorship".to_string(),
			KusamaRpcMethod::BeefyGetFinalizedHead => "beefy_getFinalizedHead".to_string(),
			KusamaRpcMethod::BeefySubscribeJustifications =>
				"beefy_subscribeJustifications".to_string(),
			KusamaRpcMethod::BeefyUnsubscribeJustifications =>
				"beefy_unsubscribeJustifications".to_string(),
			KusamaRpcMethod::ChainHeadUnstableBody => "chainHead_unstable_body".to_string(),
			KusamaRpcMethod::ChainHeadUnstableCall => "chainHead_unstable_call".to_string(),
			KusamaRpcMethod::ChainHeadUnstableFollow => "chainHead_unstable_follow".to_string(),
			KusamaRpcMethod::ChainHeadUnstableGenesisHash =>
				"chainHead_unstable_genesisHash".to_string(),
			KusamaRpcMethod::ChainHeadUnstableHeader => "chainHead_unstable_header".to_string(),
			KusamaRpcMethod::ChainHeadUnstableStorage => "chainHead_unstable_storage".to_string(),
			KusamaRpcMethod::ChainHeadUnstableUnfollow => "chainHead_unstable_unfollow".to_string(),
			KusamaRpcMethod::ChainHeadUnstableUnpin => "chainHead_unstable_unpin".to_string(),
			KusamaRpcMethod::ChainGetBlock => "chain_getBlock".to_string(),
			KusamaRpcMethod::ChainGetBlockHash => "chain_getBlockHash".to_string(),
			KusamaRpcMethod::ChainGetFinalisedHead => "chain_getFinalisedHead".to_string(),
			KusamaRpcMethod::ChainGetFinalizedHead => "chain_getFinalizedHead".to_string(),
			KusamaRpcMethod::ChainGetHead => "chain_getHead".to_string(),
			KusamaRpcMethod::ChainGetHeader => "chain_getHeader".to_string(),
			KusamaRpcMethod::ChainGetRuntimeVersion => "chain_getRuntimeVersion".to_string(),
			KusamaRpcMethod::ChainSubscribeAllHeads => "chain_subscribeAllHeads".to_string(),
			KusamaRpcMethod::ChainSubscribeFinalisedHeads =>
				"chain_subscribeFinalisedHeads".to_string(),
			KusamaRpcMethod::ChainSubscribeFinalizedHeads =>
				"chain_subscribeFinalizedHeads".to_string(),
			KusamaRpcMethod::ChainSubscribeNewHead => "chain_subscribeNewHead".to_string(),
			KusamaRpcMethod::ChainSubscribeNewHeads => "chain_subscribeNewHeads".to_string(),
			KusamaRpcMethod::ChainSubscribeRuntimeVersion =>
				"chain_subscribeRuntimeVersion".to_string(),
			KusamaRpcMethod::ChainUnsubscribeAllHeads => "chain_unsubscribeAllHeads".to_string(),
			KusamaRpcMethod::ChainUnsubscribeFinalisedHeads =>
				"chain_unsubscribeFinalisedHeads".to_string(),
			KusamaRpcMethod::ChainUnsubscribeFinalizedHeads =>
				"chain_unsubscribeFinalizedHeads".to_string(),
			KusamaRpcMethod::ChainUnsubscribeNewHead => "chain_unsubscribeNewHead".to_string(),
			KusamaRpcMethod::ChainUnsubscribeNewHeads => "chain_unsubscribeNewHeads".to_string(),
			KusamaRpcMethod::ChainUnsubscribeRuntimeVersion =>
				"chain_unsubscribeRuntimeVersion".to_string(),
			KusamaRpcMethod::ChildstateGetKeys => "childstate_getKeys".to_string(),
			KusamaRpcMethod::ChildstateGetKeysPaged => "childstate_getKeysPaged".to_string(),
			KusamaRpcMethod::ChildstateGetKeysPagedAt => "childstate_getKeysPagedAt".to_string(),
			KusamaRpcMethod::ChildstateGetStorage => "childstate_getStorage".to_string(),
			KusamaRpcMethod::ChildstateGetStorageEntries =>
				"childstate_getStorageEntries".to_string(),
			KusamaRpcMethod::ChildstateGetStorageHash => "childstate_getStorageHash".to_string(),
			KusamaRpcMethod::ChildstateGetStorageSize => "childstate_getStorageSize".to_string(),
			KusamaRpcMethod::GrandpaProveFinality => "grandpa_proveFinality".to_string(),
			KusamaRpcMethod::GrandpaRoundState => "grandpa_roundState".to_string(),
			KusamaRpcMethod::GrandpaSubscribeJustifications =>
				"grandpa_subscribeJustifications".to_string(),
			KusamaRpcMethod::GrandpaUnsubscribeJustifications =>
				"grandpa_unsubscribeJustifications".to_string(),
			KusamaRpcMethod::MmrGenerateProof => "mmr_generateProof".to_string(),
			KusamaRpcMethod::MmrRoot => "mmr_root".to_string(),
			KusamaRpcMethod::MmrVerifyProof => "mmr_verifyProof".to_string(),
			KusamaRpcMethod::MmrVerifyProofStateless => "mmr_verifyProofStateless".to_string(),
			KusamaRpcMethod::OffchainLocalStorageGet => "offchain_localStorageGet".to_string(),
			KusamaRpcMethod::OffchainLocalStorageSet => "offchain_localStorageSet".to_string(),
			KusamaRpcMethod::PaymentQueryFeeDetails => "payment_queryFeeDetails".to_string(),
			KusamaRpcMethod::PaymentQueryInfo => "payment_queryInfo".to_string(),
			KusamaRpcMethod::StateCall => "state_call".to_string(),
			KusamaRpcMethod::StateCallAt => "state_callAt".to_string(),
			KusamaRpcMethod::StateGetChildReadProof => "state_getChildReadProof".to_string(),
			KusamaRpcMethod::StateGetKeys => "state_getKeys".to_string(),
			KusamaRpcMethod::StateGetKeysPaged => "state_getKeysPaged".to_string(),
			KusamaRpcMethod::StateGetKeysPagedAt => "state_getKeysPagedAt".to_string(),
			KusamaRpcMethod::StateGetMetadata => "state_getMetadata".to_string(),
			KusamaRpcMethod::StateGetPairs => "state_getPairs".to_string(),
			KusamaRpcMethod::StateGetReadProof => "state_getReadProof".to_string(),
			KusamaRpcMethod::StateGetRuntimeVersion => "state_getRuntimeVersion".to_string(),
			KusamaRpcMethod::StateGetStorage => "state_getStorage".to_string(),
			KusamaRpcMethod::StateGetStorageAt => "state_getStorageAt".to_string(),
			KusamaRpcMethod::StateGetStorageHash => "state_getStorageHash".to_string(),
			KusamaRpcMethod::StateGetStorageHashAt => "state_getStorageHashAt".to_string(),
			KusamaRpcMethod::StateGetStorageSize => "state_getStorageSize".to_string(),
			KusamaRpcMethod::StateGetStorageSizeAt => "state_getStorageSizeAt".to_string(),
			KusamaRpcMethod::StateQueryStorage => "state_queryStorage".to_string(),
			KusamaRpcMethod::StateQueryStorageAt => "state_queryStorageAt".to_string(),
			KusamaRpcMethod::StateSubscribeRuntimeVersion =>
				"state_subscribeRuntimeVersion".to_string(),
			KusamaRpcMethod::StateSubscribeStorage => "state_subscribeStorage".to_string(),
			KusamaRpcMethod::StateTraceBlock => "state_traceBlock".to_string(),
			KusamaRpcMethod::StateTrieMigrationStatus => "state_trieMigrationStatus".to_string(),
			KusamaRpcMethod::StateUnsubscribeRuntimeVersion =>
				"state_unsubscribeRuntimeVersion".to_string(),
			KusamaRpcMethod::StateUnsubscribeStorage => "state_unsubscribeStorage".to_string(),
			KusamaRpcMethod::SubscribeNewHead => "subscribe_newHead".to_string(),
			KusamaRpcMethod::SyncStateGenSyncSpec => "sync_state_genSyncSpec".to_string(),
			KusamaRpcMethod::SystemAccountNextIndex => "system_accountNextIndex".to_string(),
			KusamaRpcMethod::SystemAddLogFilter => "system_addLogFilter".to_string(),
			KusamaRpcMethod::SystemAddReservedPeer => "system_addReservedPeer".to_string(),
			KusamaRpcMethod::SystemChain => "system_chain".to_string(),
			KusamaRpcMethod::SystemChainType => "system_chainType".to_string(),
			KusamaRpcMethod::SystemDryRun => "system_dryRun".to_string(),
			KusamaRpcMethod::SystemDryRunAt => "system_dryRunAt".to_string(),
			KusamaRpcMethod::SystemHealth => "system_health".to_string(),
			KusamaRpcMethod::SystemLocalListenAddresses =>
				"system_localListenAddresses".to_string(),
			KusamaRpcMethod::SystemLocalPeerId => "system_localPeerId".to_string(),
			KusamaRpcMethod::SystemName => "system_name".to_string(),
			KusamaRpcMethod::SystemNodeRoles => "system_nodeRoles".to_string(),
			KusamaRpcMethod::SystemPeers => "system_peers".to_string(),
			KusamaRpcMethod::SystemProperties => "system_properties".to_string(),
			KusamaRpcMethod::SystemRemoveReservedPeer => "system_removeReservedPeer".to_string(),
			KusamaRpcMethod::SystemReservedPeers => "system_reservedPeers".to_string(),
			KusamaRpcMethod::SystemResetLogFilter => "system_resetLogFilter".to_string(),
			KusamaRpcMethod::SystemSyncState => "system_syncState".to_string(),
			KusamaRpcMethod::SystemUnstableNetworkState =>
				"system_unstable_networkState".to_string(),
			KusamaRpcMethod::SystemVersion => "system_version".to_string(),
			KusamaRpcMethod::TransactionUnstableSubmitAndWatch =>
				"transaction_unstable_submitAndWatch".to_string(),
			KusamaRpcMethod::TransactionUnstableUnwatch =>
				"transaction_unstable_unwatch".to_string(),
			KusamaRpcMethod::UnsubscribeNewHead => "unsubscribe_newHead".to_string(),
		}
	}
}
