pub enum PolkadotRpcMethod {
	AccountNextIndex,
	AuthorHasKey,
	AuthorHasSessionKeys,
	AuthorInsertKey,
	AuthorPendingExtrinsics,
	AuthorRemoveExtrinsic,
	AuthorRotateKeys,
	AuthorSubmitAndWatchExtrinsic,
	AuthorSubmitExtrinsic,
	AuthorUnwatchExtrinsic,
	BabeEpochAuthorship,
	BeefyGetFinalizedHead,
	BeefySubscribeJustifications,
	BeefyUnsubscribeJustifications,
	ChainHeadUnstableBody,
	ChainHeadUnstableCall,
	ChainHeadUnstableFollow,
	ChainHeadUnstableGenesisHash,
	ChainHeadUnstableHeader,
	ChainHeadUnstableStorage,
	ChainHeadUnstableUnfollow,
	ChainHeadUnstableUnpin,
	ChainGetBlock,
	ChainGetBlockHash,
	ChainGetFinalisedHead,
	ChainGetFinalizedHead,
	ChainGetHead,
	ChainGetHeader,
	ChainGetRuntimeVersion,
	ChainSubscribeAllHeads,
	ChainSubscribeFinalisedHeads,
	ChainSubscribeFinalizedHeads,
	ChainSubscribeNewHead,
	ChainSubscribeNewHeads,
	ChainSubscribeRuntimeVersion,
	ChainUnsubscribeAllHeads,
	ChainUnsubscribeFinalisedHeads,
	ChainUnsubscribeFinalizedHeads,
	ChainUnsubscribeNewHead,
	ChainUnsubscribeNewHeads,
	ChainUnsubscribeRuntimeVersion,
	ChildstateGetKeys,
	ChildstateGetKeysPaged,
	ChildstateGetKeysPagedAt,
	ChildstateGetStorage,
	ChildstateGetStorageEntries,
	ChildstateGetStorageHash,
	ChildstateGetStorageSize,
	GrandpaProveFinality,
	GrandpaRoundState,
	GrandpaSubscribeJustifications,
	GrandpaUnsubscribeJustifications,
	MmrGenerateProof,
	MmrRoot,
	MmrVerifyProof,
	MmrVerifyProofStateless,
	OffchainLocalStorageGet,
	OffchainLocalStorageSet,
	PaymentQueryFeeDetails,
	PaymentQueryInfo,
	StateCall,
	StateCallAt,
	StateGetChildReadProof,
	StateGetKeys,
	StateGetKeysPaged,
	StateGetKeysPagedAt,
	StateGetMetadata,
	StateGetPairs,
	StateGetReadProof,
	StateGetRuntimeVersion,
	StateGetStorage,
	StateGetStorageAt,
	StateGetStorageHash,
	StateGetStorageHashAt,
	StateGetStorageSize,
	StateGetStorageSizeAt,
	StateQueryStorage,
	StateQueryStorageAt,
	StateSubscribeRuntimeVersion,
	StateSubscribeStorage,
	StateTraceBlock,
	StateTrieMigrationStatus,
	StateUnsubscribeRuntimeVersion,
	StateUnsubscribeStorage,
	SubscribeNewHead,
	SyncStateGenSyncSpec,
	SystemAccountNextIndex,
	SystemAddLogFilter,
	SystemAddReservedPeer,
	SystemChain,
	SystemChainType,
	SystemDryRun,
	SystemDryRunAt,
	SystemHealth,
	SystemLocalListenAddresses,
	SystemLocalPeerId,
	SystemName,
	SystemNodeRoles,
	SystemPeers,
	SystemProperties,
	SystemRemoveReservedPeer,
	SystemReservedPeers,
	SystemResetLogFilter,
	SystemSyncState,
	SystemUnstableNetworkState,
	SystemVersion,
	TransactionUnstableSubmitAndWatch,
	TransactionUnstableUnwatch,
	UnsubscribeNewHead,
}

impl PolkadotRpcMethod {
	pub fn as_string(&self) -> String {
		match self {
			PolkadotRpcMethod::AccountNextIndex => "account_nextIndex".to_string(),
			PolkadotRpcMethod::AuthorHasKey => "author_hasKey".to_string(),
			PolkadotRpcMethod::AuthorHasSessionKeys => "author_hasSessionKeys".to_string(),
			PolkadotRpcMethod::AuthorInsertKey => "author_insertKey".to_string(),
			PolkadotRpcMethod::AuthorPendingExtrinsics => "author_pendingExtrinsics".to_string(),
			PolkadotRpcMethod::AuthorRemoveExtrinsic => "author_removeExtrinsic".to_string(),
			PolkadotRpcMethod::AuthorRotateKeys => "author_rotateKeys".to_string(),
			PolkadotRpcMethod::AuthorSubmitAndWatchExtrinsic =>
				"author_submitAndWatchExtrinsic".to_string(),
			PolkadotRpcMethod::AuthorSubmitExtrinsic => "author_submitExtrinsic".to_string(),
			PolkadotRpcMethod::AuthorUnwatchExtrinsic => "author_unwatchExtrinsic".to_string(),
			PolkadotRpcMethod::BabeEpochAuthorship => "babe_epochAuthorship".to_string(),
			PolkadotRpcMethod::BeefyGetFinalizedHead => "beefy_getFinalizedHead".to_string(),
			PolkadotRpcMethod::BeefySubscribeJustifications =>
				"beefy_subscribeJustifications".to_string(),
			PolkadotRpcMethod::BeefyUnsubscribeJustifications =>
				"beefy_unsubscribeJustifications".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableBody => "chainHead_unstable_body".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableCall => "chainHead_unstable_call".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableFollow => "chainHead_unstable_follow".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableGenesisHash =>
				"chainHead_unstable_genesisHash".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableHeader => "chainHead_unstable_header".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableStorage => "chainHead_unstable_storage".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableUnfollow =>
				"chainHead_unstable_unfollow".to_string(),
			PolkadotRpcMethod::ChainHeadUnstableUnpin => "chainHead_unstable_unpin".to_string(),
			PolkadotRpcMethod::ChainGetBlock => "chain_getBlock".to_string(),
			PolkadotRpcMethod::ChainGetBlockHash => "chain_getBlockHash".to_string(),
			PolkadotRpcMethod::ChainGetFinalisedHead => "chain_getFinalisedHead".to_string(),
			PolkadotRpcMethod::ChainGetFinalizedHead => "chain_getFinalizedHead".to_string(),
			PolkadotRpcMethod::ChainGetHead => "chain_getHead".to_string(),
			PolkadotRpcMethod::ChainGetHeader => "chain_getHeader".to_string(),
			PolkadotRpcMethod::ChainGetRuntimeVersion => "chain_getRuntimeVersion".to_string(),
			PolkadotRpcMethod::ChainSubscribeAllHeads => "chain_subscribeAllHeads".to_string(),
			PolkadotRpcMethod::ChainSubscribeFinalisedHeads =>
				"chain_subscribeFinalisedHeads".to_string(),
			PolkadotRpcMethod::ChainSubscribeFinalizedHeads =>
				"chain_subscribeFinalizedHeads".to_string(),
			PolkadotRpcMethod::ChainSubscribeNewHead => "chain_subscribeNewHead".to_string(),
			PolkadotRpcMethod::ChainSubscribeNewHeads => "chain_subscribeNewHeads".to_string(),
			PolkadotRpcMethod::ChainSubscribeRuntimeVersion =>
				"chain_subscribeRuntimeVersion".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeAllHeads => "chain_unsubscribeAllHeads".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeFinalisedHeads =>
				"chain_unsubscribeFinalisedHeads".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeFinalizedHeads =>
				"chain_unsubscribeFinalizedHeads".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeNewHead => "chain_unsubscribeNewHead".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeNewHeads => "chain_unsubscribeNewHeads".to_string(),
			PolkadotRpcMethod::ChainUnsubscribeRuntimeVersion =>
				"chain_unsubscribeRuntimeVersion".to_string(),
			PolkadotRpcMethod::ChildstateGetKeys => "childstate_getKeys".to_string(),
			PolkadotRpcMethod::ChildstateGetKeysPaged => "childstate_getKeysPaged".to_string(),
			PolkadotRpcMethod::ChildstateGetKeysPagedAt => "childstate_getKeysPagedAt".to_string(),
			PolkadotRpcMethod::ChildstateGetStorage => "childstate_getStorage".to_string(),
			PolkadotRpcMethod::ChildstateGetStorageEntries =>
				"childstate_getStorageEntries".to_string(),
			PolkadotRpcMethod::ChildstateGetStorageHash => "childstate_getStorageHash".to_string(),
			PolkadotRpcMethod::ChildstateGetStorageSize => "childstate_getStorageSize".to_string(),
			PolkadotRpcMethod::GrandpaProveFinality => "grandpa_proveFinality".to_string(),
			PolkadotRpcMethod::GrandpaRoundState => "grandpa_roundState".to_string(),
			PolkadotRpcMethod::GrandpaSubscribeJustifications =>
				"grandpa_subscribeJustifications".to_string(),
			PolkadotRpcMethod::GrandpaUnsubscribeJustifications =>
				"grandpa_unsubscribeJustifications".to_string(),
			PolkadotRpcMethod::MmrGenerateProof => "mmr_generateProof".to_string(),
			PolkadotRpcMethod::MmrRoot => "mmr_root".to_string(),
			PolkadotRpcMethod::MmrVerifyProof => "mmr_verifyProof".to_string(),
			PolkadotRpcMethod::MmrVerifyProofStateless => "mmr_verifyProofStateless".to_string(),
			PolkadotRpcMethod::OffchainLocalStorageGet => "offchain_localStorageGet".to_string(),
			PolkadotRpcMethod::OffchainLocalStorageSet => "offchain_localStorageSet".to_string(),
			PolkadotRpcMethod::PaymentQueryFeeDetails => "payment_queryFeeDetails".to_string(),
			PolkadotRpcMethod::PaymentQueryInfo => "payment_queryInfo".to_string(),
			PolkadotRpcMethod::StateCall => "state_call".to_string(),
			PolkadotRpcMethod::StateCallAt => "state_callAt".to_string(),
			PolkadotRpcMethod::StateGetChildReadProof => "state_getChildReadProof".to_string(),
			PolkadotRpcMethod::StateGetKeys => "state_getKeys".to_string(),
			PolkadotRpcMethod::StateGetKeysPaged => "state_getKeysPaged".to_string(),
			PolkadotRpcMethod::StateGetKeysPagedAt => "state_getKeysPagedAt".to_string(),
			PolkadotRpcMethod::StateGetMetadata => "state_getMetadata".to_string(),
			PolkadotRpcMethod::StateGetPairs => "state_getPairs".to_string(),
			PolkadotRpcMethod::StateGetReadProof => "state_getReadProof".to_string(),
			PolkadotRpcMethod::StateGetRuntimeVersion => "state_getRuntimeVersion".to_string(),
			PolkadotRpcMethod::StateGetStorage => "state_getStorage".to_string(),
			PolkadotRpcMethod::StateGetStorageAt => "state_getStorageAt".to_string(),
			PolkadotRpcMethod::StateGetStorageHash => "state_getStorageHash".to_string(),
			PolkadotRpcMethod::StateGetStorageHashAt => "state_getStorageHashAt".to_string(),
			PolkadotRpcMethod::StateGetStorageSize => "state_getStorageSize".to_string(),
			PolkadotRpcMethod::StateGetStorageSizeAt => "state_getStorageSizeAt".to_string(),
			PolkadotRpcMethod::StateQueryStorage => "state_queryStorage".to_string(),
			PolkadotRpcMethod::StateQueryStorageAt => "state_queryStorageAt".to_string(),
			PolkadotRpcMethod::StateSubscribeRuntimeVersion =>
				"state_subscribeRuntimeVersion".to_string(),
			PolkadotRpcMethod::StateSubscribeStorage => "state_subscribeStorage".to_string(),
			PolkadotRpcMethod::StateTraceBlock => "state_traceBlock".to_string(),
			PolkadotRpcMethod::StateTrieMigrationStatus => "state_trieMigrationStatus".to_string(),
			PolkadotRpcMethod::StateUnsubscribeRuntimeVersion =>
				"state_unsubscribeRuntimeVersion".to_string(),
			PolkadotRpcMethod::StateUnsubscribeStorage => "state_unsubscribeStorage".to_string(),
			PolkadotRpcMethod::SubscribeNewHead => "subscribe_newHead".to_string(),
			PolkadotRpcMethod::SyncStateGenSyncSpec => "sync_state_genSyncSpec".to_string(),
			PolkadotRpcMethod::SystemAccountNextIndex => "system_accountNextIndex".to_string(),
			PolkadotRpcMethod::SystemAddLogFilter => "system_addLogFilter".to_string(),
			PolkadotRpcMethod::SystemAddReservedPeer => "system_addReservedPeer".to_string(),
			PolkadotRpcMethod::SystemChain => "system_chain".to_string(),
			PolkadotRpcMethod::SystemChainType => "system_chainType".to_string(),
			PolkadotRpcMethod::SystemDryRun => "system_dryRun".to_string(),
			PolkadotRpcMethod::SystemDryRunAt => "system_dryRunAt".to_string(),
			PolkadotRpcMethod::SystemHealth => "system_health".to_string(),
			PolkadotRpcMethod::SystemLocalListenAddresses =>
				"system_localListenAddresses".to_string(),
			PolkadotRpcMethod::SystemLocalPeerId => "system_localPeerId".to_string(),
			PolkadotRpcMethod::SystemName => "system_name".to_string(),
			PolkadotRpcMethod::SystemNodeRoles => "system_nodeRoles".to_string(),
			PolkadotRpcMethod::SystemPeers => "system_peers".to_string(),
			PolkadotRpcMethod::SystemProperties => "system_properties".to_string(),
			PolkadotRpcMethod::SystemRemoveReservedPeer => "system_removeReservedPeer".to_string(),
			PolkadotRpcMethod::SystemReservedPeers => "system_reservedPeers".to_string(),
			PolkadotRpcMethod::SystemResetLogFilter => "system_resetLogFilter".to_string(),
			PolkadotRpcMethod::SystemSyncState => "system_syncState".to_string(),
			PolkadotRpcMethod::SystemUnstableNetworkState =>
				"system_unstable_networkState".to_string(),
			PolkadotRpcMethod::SystemVersion => "system_version".to_string(),
			PolkadotRpcMethod::TransactionUnstableSubmitAndWatch =>
				"transaction_unstable_submitAndWatch".to_string(),
			PolkadotRpcMethod::TransactionUnstableUnwatch =>
				"transaction_unstable_unwatch".to_string(),
			PolkadotRpcMethod::UnsubscribeNewHead => "unsubscribe_newHead".to_string(),
		}
	}
}
