[package]
name = "types_support"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.79", default-features = false }
